stages:
  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: Build
        displayName: 'Install Dependencies'
        pool:
          name: 'Fjahangeer1872_pool'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Use Node.js'

          - script: npm install
            displayName: 'Install Dependencies'

  - stage: Test
    displayName: 'Test Stage'
    jobs:
      - job: Test
        displayName: 'Run Unit Tests'
        pool:
          name: 'ksolanki6269_pool'
        steps:
          - script: npm test
            displayName: 'Run Tests with Jest'

  - stage: Deploy
    displayName: 'Deploy Stage'
    jobs:
      - deployment: DeployFunction
        displayName: 'Deploy to Azure Function App'
        environment: production
        pool:
          name: 'Fjahangeer1872_pool'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureFunctionApp@1
                  inputs:
                    azureSubscription: 'Fjahangeer1872_lab5' # Ensure this Service Connection exists in Azure DevOps
                    appName: 'FjahangeerHttpTriggerFunction' # Name of your Azure Function App
                    package: '$(Build.ArtifactStagingDirectory)' # Path to built files
