trigger:
- main  # Trigger the pipeline on push to main branch

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: 'Build the Azure Function App'
  jobs:
  - job: Build
    steps:
    - task: UseNode@1
      inputs:
        version: '18.x'  # Ensure you're using the correct Node.js version

    - script: npm install
      displayName: 'Install dependencies'

    - script: npm test
      displayName: 'Run Unit Tests'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)'  # Archive all source files
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/functionapp.zip'
        replaceExistingArchive: true

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)/functionapp.zip'
        artifactName: 'drop'

- stage: Deploy
  displayName: 'Deploy to Azure Function App'
  jobs:
  - job: Deploy
    steps:
    - task: AzureFunctionApp@2
      inputs:
        azureSubscription: 'AzureFunctionServiceConnection'  # Service Connection Name
        appType: 'functionAppLinux'
        appName: 'myAzureFunctionApp'  # Replace with your function app name
        package: '$(Build.ArtifactStagingDirectory)/functionapp.zip'
        deploymentMethod: 'auto'